spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:mysql://localhost:3306/heimerdingers
    username: root
    password: qwe123!@#QWE
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: secret
  access-exp: 30000
  refresh-exp: 30000
  header: Authorization
  prefix: Bearer

cloud:
  aws:
    credentials:
      accessKey: AKIAUVLI3IDNZKBE3LOT
      secretKey: 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
    s3:
      bucket: gramstra
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error



${JWT_ACCESS_EXP}: 30000
${JWT_REFRESH_EXP}: 30000
${JWT_SECRET}: secret
${JWT_HEADER}: Authorization
${JWT_PREFIX}: Bearer